'use client'

import { useState } from 'react'
import { type Message } from './ChatMessage'

interface Props {
  messages: Message[]
  filename: string
}

export default function ExportReport({ messages, filename }: Props) {
  const [exporting, setExporting] = useState(false)

  const exportPDF = async () => {
    setExporting(true)
    try {
      // Dynamic imports to keep bundle lean
      const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
        import('jspdf'),
        import('html2canvas'),
      ])

      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
      const pageW = doc.internal.pageSize.getWidth()
      const margin = 18
      let y = margin

      // Header
      doc.setFillColor(26, 18, 9)
      doc.rect(0, 0, pageW, 22, 'F')
      doc.setTextColor(245, 240, 232)
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(14)
      doc.text('🐇 Talking Rabbitt', margin, 14)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8)
      doc.text(`Report generated ${new Date().toLocaleString()}  |  Source: ${filename}`, margin, 19)
      y = 32

      const aiMessages = messages.filter(m => m.role === 'assistant' || m.role === 'user')

      for (const msg of aiMessages) {
        if (y > 260) { doc.addPage(); y = margin }

        if (msg.role === 'user') {
          doc.setFillColor(237, 232, 220)
          doc.setDrawColor(181, 112, 58)
          doc.roundedRect(margin, y, pageW - margin * 2, 8, 1, 1, 'FD')
          doc.setTextColor(26, 18, 9)
          doc.setFont('helvetica', 'bold')
          doc.setFontSize(9)
          doc.text(`Q: ${msg.content}`, margin + 3, y + 5.5)
          y += 12
        } else {
          // AI answer text
          doc.setTextColor(26, 18, 9)
          doc.setFont('helvetica', 'normal')
          doc.setFontSize(9)
          const lines = doc.splitTextToSize(msg.content, pageW - margin * 2 - 6)
          doc.text(lines, margin + 3, y)
          y += lines.length * 5 + 4

          // Capture chart if present
          if (msg.chartType && msg.labels?.length) {
            const chartEl = document.querySelector(`[data-msg-id="${msg.id}"] canvas`) as HTMLCanvasElement | null
            if (chartEl) {
              try {
                const canvas = await html2canvas(chartEl, { scale: 2, backgroundColor: '#ffffff' })
                const imgData = canvas.toDataURL('image/png')
                const imgW = pageW - margin * 2
                const imgH = (canvas.height / canvas.width) * imgW
                if (y + imgH > 270) { doc.addPage(); y = margin }
                doc.addImage(imgData, 'PNG', margin, y, imgW, imgH)
                y += imgH + 8
              } catch {}
            }
          }
          y += 4
        }
      }

      // Footer
      doc.setTextColor(180, 180, 180)
      doc.setFontSize(7)
      doc.text('Generated by Talking Rabbitt · Conversational Business Analytics', margin, 290)

      doc.save(`rabbitt-report-${Date.now()}.pdf`)
    } catch (err) {
      console.error('PDF export failed:', err)
      alert('PDF export failed. Please try again.')
    } finally {
      setExporting(false)
    }
  }

  if (!messages.some(m => m.role === 'assistant')) return null

  return (
    <button
      onClick={exportPDF}
      disabled={exporting}
      style={{
        background: 'none', border: '1px solid rgba(181,112,58,0.25)', borderRadius: 4,
        padding: '4px 10px', cursor: exporting ? 'not-allowed' : 'pointer',
        fontSize: 11, fontFamily: 'var(--font-mono)', color: '#B5703A',
        display: 'flex', alignItems: 'center', gap: 5,
        textTransform: 'uppercase', letterSpacing: '0.08em',
        opacity: exporting ? 0.5 : 1,
      }}
    >
      {exporting ? (
        <><span className="dot" style={{ width: 5, height: 5 }} /> Exporting…</>
      ) : (
        <>
          <svg width="11" height="11" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          PDF Report
        </>
      )}
    </button>
  )
}
